# Dependencies
markdown:       kramdown

# Setup
title:          R Tools for Visual Studio
tagline:        'Awesome documentation'
description:    'Documentation and examples for R Tools for Visual Studio'
email:          rtvsuserfeedback@microsoft.com
url:            "https://microsoft.github.io"
baseurl:        "/RTVS-docs/"

author:
    name:       'John Lam'
    url:        https://twitter.com/john_lam

github:
    repo:       https://github.com/microsoft/RTVS-docs

gems:
  - jekyll-redirect-from