# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RTVS-Docs
email: jflam@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
    RTVS documentation and samples site
baseurl: "/RTVS-docs" # the subpath of your site, e.g. /blog
url: "https://microsoft.github.io" # the base hostname & protocol for your site
twitter_username: john_lam
github_username:  jflam

# Build settings
markdown: kramdown
